package com.mycompany.test.jdbc_connect;

import java.sql.SQLException;
import java.sql.Timestamp;
import java.util.Scanner;

public class Auto_Inc {

    public static void main(String[] args) throws SQLException {
        Scanner scanner = new Scanner(System.in);
        Jdbc_Connect jdbcConnect = new Jdbc_Connect();
        Login login = new Login();

        System.out.print("Enter your username: ");
        String username = scanner.nextLine();
        System.out.print("Enter your password: ");
        String password = scanner.nextLine();

        int userId = login.login(username, password);
        if (userId == 0) {
            System.out.println("Invalid username or password. Try again!");
        } else {
            System.out.println("Login successful!");
            System.out.println("User ID: " + userId);

            Books[] books = jdbcConnect.getBooks();
            System.out.println("Available books:");
            for (Books book : books) {
                System.out.println("Book ID: " + book.getId());
                System.out.println("Book Name: " + book.getTitle());
            }

            System.out.print("Enter the book ID you want to borrow: ");
            int bookId = scanner.nextInt();
            scanner.nextLine(); // Consume newline left-over

            Timestamp timestamp = new Timestamp(System.currentTimeMillis());

            long autoGeneratedId = jdbcConnect.autoInc(bookId, userId, timestamp);
            System.out.println("Auto-generated ID: " + autoGeneratedId);
        }
    }
}